### ISSUE TITLE
[installation] project contains the project id committed

### ISSUE THREAD

**Issue by jmolivas** [AntlerVC/firetable#118]
**Describe the bug**
The project contains the Firebase project id committed 
- `cloud_functions/.firebaserc`
- `www/.firebaserc`

**To Reproduce**
Open file `cloud_functions/.firebaserc` 

File contains
```
{
  "projects": {
    "default":"antler-vc"
  }
}
```
Open File `www/.firebaserc`
```
{
  "projects": {
    "default": "antler-vc"
  },
  "targets": {
    "antler-vc": {
      "hosting": {
        "firetable": [
          "antler-admin"
        ]
      }
    }
  }
}
```

**Expected behavior**
Files should not contain project id or maybe files should be removed, unless this is done by design for a particular reason.

**Comment by shamsmosowi** [comment]
👍 removed and added the two files to .gitignore
