### ISSUE TITLE
[deploy] package.json contains project id

### ISSUE THREAD

**Issue by jmolivas** [AntlerVC/firetable#119]
**Describe the bug**
The project contains the Firebase project id committed

**To Reproduce**
Open file `cloud_functions/functions/package.json`

```
 "deploy": "firebase deploy --token \"$FIREBASE_TOKEN\" --project antler-vc --only",
```

https://github.com/AntlerVC/firetable/blob/master/cloud_functions/functions/package.json#L10

**Comment by shamsmosowi** [comment]
thanks for the tip!, I've cleaned it up now
