### ISSUE TITLE
[deploy] deploy command is missing target

### ISSUE THREAD

**Issue by jmolivas** [AntlerVC/firetable#120]
**Describe the bug**
The deploy command is missing the target

**To Reproduce**

Ejecute deploy command 
```
yarn deploy 
```
Error output:
![image](https://user-images.githubusercontent.com/366275/81469136-32b4fd00-9198-11ea-9b21-424b74535002.png)

> The fix here is to add the target argument `functions`

```
"deploy": "firebase deploy --token \"$FIREBASE_TOKEN\" --project antler-vc --only functions",
```

**Comment by shamsmosowi** [comment]
this has been fixed with the other issues, and should no longer be a problem
