### ISSUE TITLE
[readme] missing firebase-credentials.json file expected 

### ISSUE THREAD

**Issue by jmolivas** [AntlerVC/firetable#121]
**Describe the bug**
Missing `firebase-credentials.json` file expected in the project root

```
const serviceAccount = require(`./firebase-credentials.json`);
```
https://github.com/AntlerVC/firetable/blob/master/cloud_functions/functions/fetchConfig.ts#L6

**To Reproduce**
Execute deploy command>
```
yarn deploy
```

Error
![image](https://user-images.githubusercontent.com/366275/81469387-6ba1a180-9199-11ea-81b9-afb95ae3b480.png)

**How to fix**
Add on the README.md file the steps to download a service key file from firebase console.

**Comment by shamsmosowi** [comment]
Thanks @jmolivas , I have removed the need for having service key file as a requirement, as it's only needed for a subset of optional Firetable functions that we haven't documented yet
