### ISSUE TITLE
[build] Property 'reduce' does not exist on type 'string'. 

### ISSUE THREAD

**Issue by jmolivas** [AntlerVC/firetable#122]
**Describe the bug**
The build command is not working as expected. The deploy command is also failing since is trying to execute the build command.

**To Reproduce**
Execute build command
```
yarn build
```

Error
![image](https://user-images.githubusercontent.com/366275/81469549-5c6f2380-919a-11ea-8c16-473e3d4f4a64.png)

**Comment by C-Aniruddh** [comment]
I am facing the same issue. Any updates on this?

**Comment by kx2** [comment]
I'm also facing the same issue.

**Comment by shamsmosowi** [comment]
This issue has been fixed #129
