### ISSUE TITLE
Importing text with ' results in unicode characters

### ISSUE THREAD

**Issue by harinij** [AntlerVC/firetable#15]
When uploading a CSV file with text that has ', sample below results in unicode text characters:

**Sample Input text:**
women’s health company

**Uploaded Text:**
women�s health company

**Comment by anindha** [comment]
@harinij I tried to reproduce this but couldn't. Could you please provide a link to an example csv file.

**Comment by shamsmosowi** [comment]
![image](https://user-images.githubusercontent.com/13803906/85111050-5f077300-b246-11ea-807f-57c3d35aec81.png)
![image](https://user-images.githubusercontent.com/13803906/85111066-66c71780-b246-11ea-9c23-d61a0995bb71.png)
I was able to import Unicode characters
