### ISSUE TITLE
Possibility to copy between databases/projects

### ISSUE THREAD

**Issue by dylangolow** [AntlerVC/firetable#160]
**Is your feature request related to a problem? Please describe.**
A use case I have built scripts for in the past is copying data for tests or otherwise between projects/databases in firestore.

**Describe the solution you'd like**
The ability to add additional firebase project ids and then given a selection, you can copy/migrate data to another project.

**Describe alternatives you've considered**
Custom function using firebase shell to copy between projects and allow service account access to service project from host project. 

**Additional context**
...

**Comment by shamsmosowi** [comment]
hi @dylangolow this is currently outside of the scope of firetable UI, we do have a callable and a cron cloud functions to export firestore data and incomplete restore from backup callable function [here](https://github.com/AntlerVC/firetable/blob/master/cloud_functions/functions/src/backup.ts).  you also use `gcloud` cli to import the data back into firestore ```gcloud firestore import gs://[STORAGE_BUCKET]/[DATE_FOLDER]```
