### ISSUE TITLE
Getting 404 for http://localhost:5000 after firetable start | Platform: Fedora 31

### ISSUE THREAD

**Issue by sumitkumar2019** [AntlerVC/firetable#187]
After Project Set up and Performing below operation, I am getting 404 for http://localhost:5000
cd [directory]
firetable start

**Comment by shamsmosowi** [comment]
Hi, can you try updating the CLI to 1.0.1 and try again, it should work as expected now. Let me know if you're still having issues with it

**Comment by sumitkumar2019** [comment]
ok let me try

**Comment by sumitkumar2019** [comment]
@shamsmosowi it is working after updating version to 1.0.1. Node version 10.15

npm install firetable@1.0.1

Thank you :+1:

**Comment by sumitkumar2019** [comment]
@shamsmosowi Now I am getting Error on the page while login through google credentials: I am login with credential who is owner of the project

You need to enable Google authentication in your firebase project

**Comment by sumitkumar2019** [comment]
@shamsmosowi It seems o be known issue

https://github.com/AntlerVC/firetable#known-issue-this-account-does-not-have-any-roles

Thank you for your help on this :+1:
