### ISSUE TITLE
Column sizing issue

### ISSUE THREAD

**Issue by harinij** [AntlerVC/firetable#19]
Occasionally column sizes are getting extended to infinite width

**Comment by shamsmosowi** [comment]
https://github.com/adazzle/react-data-grid/pull/1700#thread-subscription-status
Looks like it's the data-grid library issue, it's already fixed waiting for the pull request to be approved

**Comment by shamsmosowi** [comment]
https://github.com/adazzle/react-data-grid/pull/1700#thread-subscription-status
Looks like it's the data-grid library issue, it's already fixed waiting for the pull request to be approved

**Comment by AntlerEngineering** [comment]
fixed with the new datagrid upgrade
