### ISSUE TITLE
yarn start : turned in to error during start of application| Platform: Fedora 31

### ISSUE THREAD

**Issue by sumitkumar2019** [AntlerVC/firetable#190]
./node_modules/react-data-grid-addons/lib/toolbars/GroupedColumnsPanel.js
Attempted import error: 'DragItemTypes' is not exported from 'react-data-grid'.

**Comment by shamsmosowi** [comment]
are you sure your using yarn or npm? because the `react-data-grid` library has this issue you use `npm` instead of `yarn`
