### ISSUE TITLE
Error Please Help

### ISSUE THREAD

**Issue by carelkat** [AntlerVC/firetable#210]
Hi there, I would really like to use this, but I get this error. Please be so kind and have a look. I am quite new to Firebase and Java, so please be patient. 

Thank you

![Firetable_error](https://user-images.githubusercontent.com/29289579/93932840-123da780-fd21-11ea-9aad-0e647ddcdacd.png)

**Comment by carelkat** [comment]
Can just also note that if I do go into Users I do find the Firetable folder,and if I go into public I do see the Index page but if I open it it is just blank.

**Comment by notsidney** [comment]
Hey there, it looks like you’re running an old version of the Firetable CLI, which didn’t work on Windows. Please try upgrading using
```
yarn global add firetable
```
and running again

**Comment by carelkat** [comment]
Thank you, I did that but got the same error.
![firetable_nodejs](https://user-images.githubusercontent.com/29289579/94368062-83df7200-00e2-11eb-933c-42f4c7f2cf40.jpg)

**Comment by notsidney** [comment]
@carelkat could you please check that it’s running the correct version? The command for that is:
```
firetable -V
```

If it’s not 1.1.0, you can try reinstalling Firetable CLI with these commands:
```
yarn global remove firetable
yarn global add firetable
```

**Comment by notsidney** [comment]
@carelkat I’ve updated the CLI to version 1.1.1. Please update and make sure you’re running the latest version using the instructions above.
