### ISSUE TITLE
cannot log in on new project

### ISSUE THREAD

**Issue by jonathan-chin** [AntlerVC/firetable#211]
Hi, I just started a new firetable project using `firetable init`
I can start and serve it locally no problem. when I visit it in the browser, I get a login page and I try to login with my Google credentials. However, I get the following error: `You need to enable Google authentication in your firebase project`. I went to my console and enabled Google authentication and try logging in again. However, I get the same error.

I've looked at my auth tab in the Firebase console and can see indeed my Google account created a new user (timestamp matches today). I even stopped serving and tried reserving it. I still get the same error: `You need to enable Google authentication in your firebase project`

**Comment by jonathan-chin** [comment]
I think this may have been caused by me enabling google authentication after running `firebase init`
I deleted my firetable instance and init'ed a new one and it's fixed
for future reference, is there a way to fix it if I enable google auth after init?

**Comment by shamsmosowi** [comment]
I don't think it's necessary redo the setup, a hard refresh should have been enough

**Comment by jonathan-chin** [comment]
> I don't think it's necessary redo the setup, a hard refresh
> after changing the auth settings should have been enough

what do you mean by 'hard refresh'?

**Comment by shamsmosowi** [comment]
[this](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/), it's used for clearing the browser cache.

**Comment by jonathan-chin** [comment]
got it. will try next time. though, I usually try control-R if I suspect a caching issue. don't remember if I tried it this time.
