### ISSUE TITLE
Free text for single-select not working

### ISSUE THREAD

**Issue by jfr3000** [AntlerVC/firetable#217]
**Describe the bug**
When editing the settings for a single-select column, the admin is given the choice to enable adding new select-options for other users. While this works for multi-select, it doesn't for single-select - on purpose, [it seems?](https://github.com/AntlerVC/firetable/blob/fd036f59c7111b5105d69f94d183ccb1439eb0b7/www/src/components/Table/formatters/MultiSelect.tsx#L121).
If so, perhaps the UI should be updated to not offer this option, when it doesn't exist. Or better, enable it for single-select which would be very useful :)

**To Reproduce**
1. As admin, add a column and set it to single-select.
2. Go to column settings, and enable "User can add new options."
3. Log in as non-admin user and try to add a new select option.

**Expected behavior**
Expect to be able to add a new select option when it was enabled by the admin.

**Comment by notsidney** [comment]
Weird, I’m not sure why I left this disabled in the first place. I’ve removed this restriction in 4dbf29d
