### ISSUE TITLE
Unable to unhide a column that was hidden using column settings

### ISSUE THREAD

**Issue by mellissatort** [AntlerVC/firetable#218]
**Describe the bug**
Within the column settings a user can choose to hide a column.  Once the column is hidden the user is not able to unhide the column from the firetable UI.  Even trying to use the "Hide" button on the table does not allow the column to be unhidden.  

**To Reproduce**
1. Identify a column to hide
2. Click on down arrow for the column to display the config options
3. Select the "Hide" option.  The column is now no longer visible in the table view but is still visible in the form view.
4. On the table view, select the "Hide" button
5. The column that was previously hidden is still showing as visible based on the "Hide" settings.
6. Enable/disable the "Hide" option for the column and see that when you return to the table view the column still is not visible

**Expected behavior**
If a column is hidden, the user should be able to unhide it using the table view "Hide" button or some other method to update the column settings from the fireable UI

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Safari
 - Version: 13.1

**Comment by shamsmosowi** [comment]
thanks for flagging this @mellissatort , it'll be fixed in the next merge #216
