### ISSUE TITLE
CSV import for a DATE column results in "Something went wrong" displayed in firetable

### ISSUE THREAD

**Issue by mellissatort** [AntlerVC/firetable#219]
**Describe the bug**
A column in firetable is configured with the DATE type.  When importing a CSV file with date data into this field, the result is "Something went wrong" is displayed.  Several different date formats have been tried.

**To Reproduce**
1. Create a firetable with a column of type DATE 
2. Import a csv file with a column having data in a date format into this DATE column.  The following formats have been attempted:
- m/d/yy
- mm/dd/yy
- mm/dd/yyyy
- month day, yyyy
- yyyy-mm-ddT00:00:00.000Z
- yyyy-mm-ddT00:00:00Z
3. The import will be successful but the firetable will display "Something went wrong" for this date value.

After manually entering a record into the firetable, we reviewed the data being stored via firebase and the date value is being stored as a timestamp instead of just a date.  Exported the table data to confirm the format from an export and it is yyyy-mm-ddT00:00:00.000Z which is one of the formats listed above that was tried for importing.

**Expected behavior**
Firetable import will accept any date format, or a defined date format that is supported for import needs to be identified.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Safari
 - Version: 13.1

**Comment by grzegorzbialy** [comment]
I stumbled upon same issue while trying to import dates. 
Until the issue is solved you can use onCreate trigger to correct the date.

Eg.:
`exports.onSlotCreate = functions
  .firestore.document('docs/{docId}')
  .onCreate(async (snapshot, context) => {
    const docData = snapshot.data();
    let update = false;

    if (typeof docData.date === "string") {
      docData.date = new Date(docData.date);
      update = true;
    }

    if (update) {
      db.collection('docs').doc(snapshot.id).update({date: docData.date});
    }
  });`

**Comment by mayurdhurpate** [comment]
@notsidney I think, all the fields are being imported as strings in the Firestore, and hence the Data Parser shows `Something went wrong` in the Date call. 

I tried importing the following fields:
 - name : string
 - profilePictureUrl : string
 - rating : number
 - review : string
 - reviewId : string
 - timestamp : Date

with following csv:
```
name,profilePictureUrl,rating,review,reviewId,timestamp
Madhuri Salunkhe,,5,,temp_review,11/11/2020
```

**Data Key Mapping Screen:**

![Screenshot 2020-10-08 at 7 59 21 PM](https://user-images.githubusercontent.com/10077074/95472718-000a6d00-09a1-11eb-876c-78f4f4bb5aa9.png)

**Firetable Post Import Screen**

![Screenshot 2020-10-08 at 7 59 54 PM](https://user-images.githubusercontent.com/10077074/95472794-11ec1000-09a1-11eb-9a86-2947de507c47.png)

**Actual Firestore Data Stored:**

![Screenshot 2020-10-08 at 8 00 08 PM](https://user-images.githubusercontent.com/10077074/95472879-29c39400-09a1-11eb-983e-9c1584f4d6e3.png)


**All the fields were directly added to Firestore as strings.**

I think this could be the function which needs modification for type aware data importing.
https://github.com/AntlerVC/firetable/blob/fd036f59c7111b5105d69f94d183ccb1439eb0b7/www/src/components/Table/ImportCSV.tsx#L96-L105

**Comment by notsidney** [comment]
Hi everyone, thanks for letting us know about this bug. I’m working on a new Import CSV wizard UI, which includes parsing date columns. We’ll be using date-fns’ `parseJSON` function, which supports a [bunch of formats similar to the ISO date string format](https://date-fns.org/v2.16.1/docs/parseJSON). Please note that it **assumes your date is in UTC time**, so if your CSV’s date is not in UTC and your browser/system’s timezone is not UTC, Firetable (and Firestore) will display a different date/time value (converted from UTC to your local timezone).

👉 So before using the Import CSV feature, **you must convert dates to UTC time and a [supported format](https://date-fns.org/v2.16.1/docs/parseJSON)**.

When rows are added, it will store dates as [Firestore Timestamps](https://firebase.google.com/docs/reference/js/firebase.firestore.Timestamp), similar to adding a new row & inputting a date through the picker.

The new Import CSV wizard will be available as part of the next PR from develop to master.
