### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by jaykay-git** [AntlerVC/firetable#222]
About these [instructions](https://github.com/AntlerVC/firetable/blob/master/cli/README.md#Setting-user-Roles):

> 'Download the admin key for your project then add it to the directory without renaming it.'

1) Cannot find anything in project settings called "admin key".  Do you mean **generate a new private key** for the **Admin SDK**?

2) What do you mean "add it" to "the directory"?  Do you mean **move it** (the downloaded .json file) to the **www** directory (or somewhere else)?

About these [instructions](https://github.com/AntlerVC/firetable/blob/master/RULES.md):

3) What does "firestore rules you" mean?

> 'Firetable uses a Role based access control on top of **firestore rules you**.'

**Comment by shamsmosowi** [comment]
clarified 1,3 in #224, 2 the directory of where your terminal is running

**Comment by jaykay-git** [comment]
> the directory of where your terminal is running

That is called either the "[current directory](http://www.linfo.org/current_directory.html)" or the "[working directory] (https://www.gnu.org/software/libc/manual/html_node/Working-Directory.html)"
