### ISSUE TITLE
Enable the Google sign-in method in Authentication / Sign-in

### ISSUE THREAD

**Issue by jaykay-git** [AntlerVC/firetable#225]
Regarding these "[Setup Instructions](https://github.com/AntlerVC/firetable#setup-instructions)" ...

> - Enable the Google sign-in method in Authentication / Sign-in method
> 
> ⚠️ IMPORTANT: If you try to sign in and see “This account does not have any roles”, run the following script on your Firebase Authentication user.

1) There is nothing on the **Authentication / Sign-in** page called "Firebase Authentication user". 

2) There are no apparent fields on the **Authentication / Sign-in** page to "run the following script".

**Comment by notsidney** [comment]
Hi @jaykay-git, these are two separate steps.

1. You need to [enable the Google sign-in method in the Firebase Console.](https://console.firebase.google.com/project/_/authentication/providers)

2. To fix the “This account does not have any roles” issue, [follow these instructions.](wiki/Firetable-Role-Based-Security-Rules#set-user-roles-with-the-firetable-cli)

I hope the updated documentation is more helpful for you.
