### ISSUE TITLE
Instructions says to upgrade firebase project to 'Blaze Plan'

### ISSUE THREAD

**Issue by shashishringari** [AntlerVC/firetable#226]
**Describe the bug**
Instructions says to upgrade firebase project to 'Blaze Plan'. However, there is no reason or consequences mentioned. Will Project not work if I am not on Blaze plan? and reason for moving to Blaze plan not mentioned. I am trying to explore this solution. But as I am just starting, I am hesitant to move to Blaze plan. Please help.

**To Reproduce**
Readme instructions

**Expected behavior**
Explain in a sentence on why Blaze plan is needed.

**Screenshots**
not needed

**Desktop (please complete the following information):**
Firebase Project

**Smartphone (please complete the following information):**
All

**Additional context**

**Comment by shamsmosowi** [comment]
Hi, you can start with the Free plan, as the blaze plan is only needed for some cloud functions. We used to have the table export feature running on a cloud function, but we have moved it to completely be running on the frontend. We do have some columns that require cloud functions at the moment, but they're still undocumented so you'll probably not be using them just yet.

**Comment by shashishringari** [comment]
Thank you! Thanks for clarification! I am leaving it open in case you want to document in readme or free to close it.

**Comment by notsidney** [comment]
Hi @shashishringari, thanks for pointing it out. We’re planning on upgrading our documentation, so we’ll definitely be adding this to make it easier for people to get started. If there are any other points we missed in our current instructions, please let us know here!
