### ISSUE TITLE
Add this project to firebaseopensource.com

### ISSUE THREAD

**Issue by samtstern** [AntlerVC/firetable#229]
Hi there!  I'm from the Firebase team and I saw your project making the rounds, it looks fantastic!

I also maintain https://firebaseopensource.com which is a repository of open source projects that use Firebase.  I'd love to add Firetable to the site, if you're interested.

All you have to do is add a file called `.opensource/project.json` to your repo with some basic information.

Here are some examples:
https://github.com/Flank/flank/blob/master/.opensource/project.json
https://github.com/jsayol/FireSQL/blob/master/.opensource/project.json

Really the only required field is `content`, so this shouldn't require much work!

**Comment by AntlerEngineering** [comment]
Thanks for reaching out @samtstern. We would love to get added to the list of open source projects on firebase and will add the file to our repo shortly. 👍

**Comment by harinij** [comment]
Thanks for reaching out @samtstern We would love to get added to the list of open source projects on firebase and will add the file to our repo shortly. 👍

We are actively working on this project and have in the roadmap many exciting new features to allow developers to build on top of firebase and ship faster. Connected to you ok LinkedIn to see if there is opportunity to collaborate further.

**Comment by samtstern** [comment]
@harinij great!  I don't actually used LinkedIn but my email is in my GitHub profile, feel free to reach out.

**Comment by notsidney** [comment]
Hi @samtstern, we added the file in f0341bf

**Comment by samtstern** [comment]
@notsidney awesome!  Added you to the site:
https://github.com/firebase/firebaseopensource.com/commit/d9914041fcc04ba634e150109c311b86dd8c1d70

The site is built every 24 hours so your page should appear soon.
