### ISSUE TITLE
Failed to build and serve

### ISSUE THREAD

**Issue by justshreyas** [AntlerVC/firetable#232]
**Describe the bug**
Firetable Build did not succeed

**To Reproduce**
1. Run ```firetable start``` in the created firetable project directory
2. Open Browser and go to ```http://localhost:5000``` 

**Expected behavior**
See a login/welcome screen in the browser window after CLI shows "Serving Firetable at http://localhost:5000"

**Actual Behavior**
CLI shows "Serving Firetable at http://localhost:5000"
404 page  in the browser window

**Insights**
1. Build is not successful, since there seems to be no build folder inside ```www```
2. ```yarn doctor``` shows error : Couldn't find a package.json file in "my/location/of/project"

**Desktop**
 - OS: Windows 10 (build: 19041.508, September 2020)
 - Browser: Google Chrome (version 85.0.4183.121), Microsoft Edge (version 85.0.564.68)

**Additional context**
1. ```npm -v``` 6.7.0
2. ```yarn -v``` 1.22.5
3. ```node -v``` v11.15.0
4. ```firebase --version``` 8.11.2
5. ```firetable -V``` 1.1.2

**Issues and comments referenced**
1. #188 
2. #191 
3. #187

**Comment by notsidney** [comment]
Hi @justshreyas, could you please try running `yarn build` inside the `www` directory? Once that builds, try running `firetable start` again. Please let me know if this works.

**Comment by justshreyas** [comment]
Thanks a lot for the prompt response. This worked.
