### ISSUE TITLE
Create an option to add generic data types to cover complex (Map and Array type) Firestore data fields

### ISSUE THREAD

**Issue by mayurdhurpate** [AntlerVC/firetable#233]
**Is your feature request related to a problem? Please describe.**
When I'm adding Firestore to my existing projects, there are many nested data types (calling them `complex data field`s henceforth) which could not be mapped to Firetable, thus making it impossible for me to give access to edit those fields to my content/marketing teams. Following are some of the examples:
 - Firestore `Map` Field containing key-value pairs of different data types (`string`, `boolean`, `number`)
 - Firestore `Array` of `Text` and/or `number`
 - Firestore `Array` of `Map`s containing different data types   

These `complex data field`s are analogous to different permutations and combinations of a JSON type object.

**Describe the solution you'd like**
Adding JSON like generic field `column` which takes care of adding, editing, and updating the data for these `complex data field`s. 

**Describe alternatives you've considered**
It is possible to remodel these fields as JSON `string` field supported by Firetable, but that would require a lot of development effort. I'm also considering a Cloud Function triggered on editing a JSON object which adds it to the complex data fields. But given how frequently such cases may be encountered, an out of the box solution providing basic support to edit them would be much more helpful.

**Additional context**
There are workarounds for many other issues, but this one acts as a blocker for us to use Firetable to it's fullest! Love the product, great effort by @AntlerEngineering team!

**Comment by a-Leong** [comment]
@mayurdhurpate After some investigation I believe the functionality you're describing is already implemented, though I could be misunderstanding. Have you tried using the JSON column type and editing the value in the column-editing side menu? I am able to add and edit string and number arrays, maps with key-value pairs of different data types, etc.

<img width="935" alt="Screen Shot 2020-12-10 at 5 16 35 PM" src="https://user-images.githubusercontent.com/13441245/101848982-9ecf5900-3b0b-11eb-858d-ff6b3194f1da.png">

**Comment by mayurdhurpate** [comment]
Yes, looks like now this feature is added. I just tried with different permutations, it works perfectly! Closing it.
