### ISSUE TITLE
Option to view, modify and export document ids

### ISSUE THREAD

**Issue by mayurdhurpate** [AntlerVC/firetable#234]
**Is your feature request related to a problem? Please describe.**
For many of our collections, `document id`s are the primary way for us to search and work on documents. For some of the collections, we provide custom `document id`s instead of automatic `document id`s created by Firestore. 

Currently, it is not possible to view and export `document id`s in the Firetable table for any collection. 

**Describe the solution you'd like**
Though, the id can be accessed by clicking on a document, providing a (freezed/locked) access to them in Firetable `table` view would be very helpful. Also, while creating a new row, an option may be provided to use a custom id instead of the default id generated by Firetable

**Comment by notsidney** [comment]
Hi @mayurdhurpate, these are great suggestions! If it helps, we expose the document path (which includes the document ID) right at the bottom of the side drawer, with a link to open it in the Firebase Console.
![image](https://user-images.githubusercontent.com/27017118/95185537-8cd3f000-0814-11eb-9bba-700da1824ad6.png)

**Comment by notsidney** [comment]
Added ID field type in e0d0178

**Comment by johnfuller** [comment]
I don't know if I found a hidden feature. But I created a column called "id" with a "short text" type and the document ID auto-fills for each row. This was pulled around a week ago from master. I haven't updated since then, so I haven't tried the change referenced in e0d0178.

**Comment by a-Leong** [comment]
> Also, while creating a new row, an option may be provided to use a custom id instead of the default id generated by Firetable

Is it possible to add a row with a custom ID? If not, I'm happy to open a new ticket

**Comment by notsidney** [comment]
Hi @a-Leong, we haven’t worked on implementing this yet, but we have a design ready. It must have slipped through when I implemented the ID field and closed this issue prematurely. Please create a new issue, thanks
