### ISSUE TITLE
Import Wizard not showing up for existing collections

### ISSUE THREAD

**Issue by torbjornvatn** [AntlerVC/firetable#235]
**Describe the bug**
I just tested this the same scenario as described in #208 locally and the Wizard doesn't show up for me either.
I just get a blank row (no column and no value) for the one test document I added to my test collection that has the same name as the table I'm trying to create

**To Reproduce**
Add a table with the same name as an existing collection

**Expected behavior**
That the Import Wizard should show up

**Additional context**
If I delete the single "empty" row that shows up in the UI, my existing test document is also deleted. Which is a bit sketchy if someone tests this on an existing production database.

**Comment by notsidney** [comment]
Hi @torbjornvatn, thanks for pointing this out. It looks like there’s a bug where adding new tables initialises the column config as an empty Firestore map `{}`, which doesn’t return as `false` in the JS that triggers the import wizard to appear.

We’re also working on updating the empty table UI to be less empty—I’ll be adding a button to manually open the import wizard.

I’m not sure if something went wrong with deleting the single empty row—that button is always meant to delete the associated Firestore document for that row. We can add a confirmation dialog to prevent users accidentally doing this, but this should be secured with Firestore rules.
