### ISSUE TITLE
Height dropdown option not working and resets itself on demo page

### ISSUE THREAD

**Issue by kanhegaonkarsaurabh** [AntlerVC/firetable#242]
**Describe the bug**
The height dropdown option is not working and upon selecting a new option, after a second or so the dropdown resets to the original default option "Venti"

**To Reproduce**
1. Go to 'https://try.firetable.io/table/mvpResources?rowRef=mvpResources%2F1wqXmWaneac5kyzYm5bb'
2. Click on dropdown Height to select a different height (For ex: Tall)
3. See error

**Expected behavior**
The expected behavior should be that the height option does not reset itself to the default option and instead the height of the rows gets set to the one the user selected. 

**Screenshots**

![gif-bug](https://user-images.githubusercontent.com/25760507/95699298-f24f2480-0bf8-11eb-8407-e338f9a6ed0c.gif)

**Desktop (please complete the following information):**
 - OS: macOS Cataline 10.15.3
 - Browser Chrome
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by notsidney** [comment]
Hi @kanhegaonkarsaurabh, this is because you’re not signed in.
