### ISSUE TITLE
Tabbing thru table cells does not automatically adjust the horizontal scroll bar

### ISSUE THREAD

**Issue by mellissatort** [AntlerVC/firetable#257]
**Describe the bug**
When a table has more cells than displayed on the screen, if the user is tabbing to the right thru the cells, the horizontal scroll bar does not move in line with the tabbing.  When the user tabs to the left the scroll bar does move in line with the tabbing.

**To Reproduce**
1. Go to a table containing more columns than displayed in a window
2. Select the first cell in the table
3. Use the [tab] key to tab to the right thru the row cells.  Notice the table horizontal scroll bar does not move in line with tabbing
4. Manually scroll to the right in the table view
5. Use the [shift]+[tab] key to tab to the left thru the row cells.  Notice the table horizontal scroll bar does move in line with the tabbing

**Expected behavior**
The horizontal scroll bar should move in line with the tabbing when tab to the right or left

**Desktop (please complete the following information):**
 - OS: iOS 10.14.6
 - Browser Chrome
 - Version 86.0.4240.111

**Comment by notsidney** [comment]
Hi @mellissatort, this is fixed as part of an update to react-data-grid. It will be part of pull request #254 to be merged sometime this week.
