### ISSUE TITLE
Keyboard navigation is active while having focus in the input 

### ISSUE THREAD

**Issue by zdebra** [AntlerVC/firetable#260]
**Describe the bug**
There is apparently a keyboard navigation bug when a new item to the `Accessed By` field is being added. If you write `ADMIN` the input loses its focus and a button on the background is highlighted. This makes it impossible to input anything starting with `a`.

This is probably also happening for other characters involved in keyboard navigation if this is the source of the bug.

**To Reproduce**
1. Go to Create Table wizard
2. Open `Accessed By` select box
3. Click Add New
4. Try to type something starting on `a` to the input in the modal

**Expected behavior**
I can write `ADMIN` into the text input.

**Screenshots**
![image](https://user-images.githubusercontent.com/14963369/98295554-072d9680-1fb2-11eb-958e-7f69f3265b1c.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser chrome
 - Version 86.0.4240.111

**Additional context**
You can copy&paste to the input field as a workaround.

**Comment by shamsmosowi** [comment]
Thanks @zdebra for flagging this, it has been fixed in the latest release, which is available on the master branch now
