### ISSUE TITLE
After table is created and site exited cannot reopen table, continual loading

### ISSUE THREAD

**Issue by liveaffiliates** [AntlerVC/firetable#261]
Hi, this is an awesome project thanks for taking the time to make it. It is very much needed. 

**Describe the bug**
Upon first installation and table creation (both loading existing and new through csv) everything works as normal and the table is created. 

Then after exiting from the hosting or local host where the table is created and reopening, the table does not get added to the menu and the home screen just says + or add new table as if it was never created. If you then go to the url of the table itself it just continuously loads and the table does not appear.

**To Reproduce**
1. Open Firetable on local host or on google hosting.
2. Create a new table.
3. Wait for it to finishing creating the collection in the database.
4. Close the browser.
5. Reopen firetable.

**Expected behavior**
Expected behaviour the table is is created and can be accessed again

**Screenshots**
![Screen Shot 2020-11-08 at 5 40 43 pm](https://user-images.githubusercontent.com/15039954/98461813-46462c80-21ea-11eb-92eb-d3900d94ee93.png)
![Screen Shot 2020-11-08 at 5 40 43 pm](https://user-images.githubusercontent.com/15039954/98461831-71308080-21ea-11eb-98f5-91896aa5019d.png)

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: Chrome and Firefox

**Comment by notsidney** [comment]
Hi @liveaffiliates, it looks like the Firetable config isn’t being stored properly in your Firestore database. Could you please check that:
1. There is a document with the path `/_FIRETABLE_/settings/schema` that contains a `tables` field
2. If not, check that your Firestore Rules include our required rules: https://github.com/AntlerVC/firetable/wiki/Role-Based-Security-Rules#required-firetable-rules

**Comment by liveaffiliates** [comment]
@notsidney Hi, thanks for that. Yes this was the problem. The individual collections only had write permissions on signed in. But there was not permission to create the new collections.
