### ISSUE TITLE
App name in manifest.json

### ISSUE THREAD

**Issue by wzulfikar** [AntlerVC/firetable#265]
Hey there, should we change the name in `manifest.json` to "Firetable" / "Create Firetable App" accordingly (line 2-3)? Or it's intentionally left for the default "React App" / "Create React App Sample"?

https://github.com/AntlerVC/firetable/blob/75a0f03874c7de69095c13eedb0438e356f3732f/www/public/manifest.json#L1-L9

**Comment by shamsmosowi** [comment]
updated, thanks for flagging it!
