### ISSUE TITLE
Module not found: Can't resolve 'react-data-grid/lib/hooks'

### ISSUE THREAD

**Issue by Rohitbels** [AntlerVC/firetable#273]
**Describe the bug**
Failed to compile.

./src/components/Table/ColumnHeader.tsx
**Module not found: Can't resolve 'react-data-grid/lib/hooks'** in 'D:\firetable\www\src\components\Table'

**To Reproduce**
I have the latest master pulled.
I did try deleting node_modules and reinstalling but no avail.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

cc: @shamsmosowi  https://github.com/AntlerVC/firetable/commit/a2cff390ec8475a258ea88cb8eb6322958826528

**Comment by notsidney** [comment]
Could you please check which version of react-data-grid is installed? Check the version field in `www/node_modules/react-data-grid/package.json`. Alos make sure you’re installing dependencies using yarn, since we don’t have an npm `package-lock.json` file

**Comment by Rohitbels** [comment]
> Also make sure you’re installing dependencies using yarn, since we don’t have an npm `package-lock.json` file
Did the trick
