### ISSUE TITLE
"Something went wrong" creating a new table

### ISSUE THREAD

**Issue by Andrew565** [AntlerVC/firetable#276]
**Describe the bug**
I'm setting up Firetable for the first time. Followed the "Getting Started" guide, used the Firetable CLI route, started up just fine, got an empty interface save for the "Create a new table" button, clicked it, and got "SOMETHING WENT WRONG
undefined is not an object (evaluating 'f[0]')".

**To Reproduce**
1. Go to 'Home Screen'
2. Click on 'Create a new table'
3. See an error

**Expected behavior**
Expected to be treated to the "create a new table" interface.

**Screenshots**
<img width="368" alt="Screen Shot 2020-12-07 at 21 35 49" src="https://user-images.githubusercontent.com/147893/101431606-3c8d1300-38d5-11eb-96e8-c2b4808298d3.png">
<img width="933" alt="Screen Shot 2020-12-07 at 21 39 36" src="https://user-images.githubusercontent.com/147893/101431703-634b4980-38d5-11eb-832a-89ee0f6c0fbb.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Chrome
 - Version: 87.0.4280.67

**Additional context**
I had a pre-existing Firebase account but set up Firetable using a brand-new project. According to the stack trace, this may have something to do with the MultiSelect component, but a quick look at the source code didn't immediately reveal any culprits. My theory is that there may be some kind of disconnect somewhere where a data look-up is assuming there will already be a table in the system, and fails un-gracefully when it doesn't find one.

**Comment by willkuerlich** [comment]
![Same here](https://user-images.githubusercontent.com/8741947/101558565-8520fb00-39bf-11eb-9aeb-204b879b7031.png)

I noticed that the webhook url is prefixed with undefined...

![image](https://user-images.githubusercontent.com/8741947/101558779-fc568f00-39bf-11eb-93c0-806c51ed0d84.png)

Also I would like to mention that I am using a spark project without cloud functions, does this matter? - Is firetable dependent on the presence of cloud functions?

**Comment by willkuerlich** [comment]
> **Describe the bug**
> I'm setting up Firetable for the first time. Followed the "Getting Started" guide, used the Firetable CLI route, started up just fine, got an empty interface save for the "Create a new table" button, clicked it, and got "SOMETHING WENT WRONG
> undefined is not an object (evaluating 'f[0]')".
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'Home Screen'
> 2. Click on 'Create a new table'
> 3. See an error
> 
> **Expected behavior**
> Expected to be treated to the "create a new table" interface.
> 
> **Screenshots**
> <img alt="Screen Shot 2020-12-07 at 21 35 49" width="368" src="https://user-images.githubusercontent.com/147893/101431606-3c8d1300-38d5-11eb-96e8-c2b4808298d3.png">
> <img alt="Screen Shot 2020-12-07 at 21 39 36" width="933" src="https://user-images.githubusercontent.com/147893/101431703-634b4980-38d5-11eb-832a-89ee0f6c0fbb.png">
> 
> **Desktop (please complete the following information):**
> 
> * OS: macOS 10.15.7
> * Browser: Chrome
> * Version: 87.0.4280.67
> 
> **Additional context**
> I had a pre-existing Firebase account but set up Firetable using a brand-new project. According to the stack trace, this may have something to do with the MultiSelect component, but a quick look at the source code didn't immediately reveal any culprits. My theory is that there may be some kind of disconnect somewhere where a data look-up is assuming there will already be a table in the system, and fails un-gracefully when it doesn't find one.

What kind of Firebase project Plan do you use?

**Comment by mulyoved** [comment]
Having the same problem, Blaze plan (Pay as you go)

OS: Linux
New/Empty Firebase project, the only collection I have is _FT_USERS

**Comment by willkuerlich** [comment]
Base on the error stack, the optionsProps array seems to be empty or missing. Right now I don't have the time, but I will investigate on this issue on the weekend. Has anyone a clue, what optionProps are expected there or where they would have been coming from usually?

**Comment by GustavoMelo40** [comment]
I believe it is related to some collection / document that is not present in the firebase. Take this once I created something in the firestore and solved it, some null / empty array field that is trying to access the first position

**Comment by GustavoMelo40** [comment]
The problem Multiseletic is the Rules Selector!

**Comment by shamsmosowi** [comment]
It looks this is a bug when creating a new table for the first time, as it expects an array of tables to already exist, fixed on the RC branch atm

**Comment by GustavoMelo40** [comment]
Not work @shamsmosowi , same error =/

**Comment by ahmadalibaloch** [comment]
Same error, blaze plan, and everything setup.

**Comment by mulyoved** [comment]
@shamsmosowi Fix form RC branch worked for me

**Comment by ahmadalibaloch** [comment]
working fine on develop branch.

**Comment by Twansparant** [comment]
I've got the same error, also with the develop/rc branch?

**Comment by Twansparant** [comment]
Ah, when I manually add a collection named `_FIRETABLE_` with a `settings` document to my **Firestore**, all the errors are gone and I can create new tables!

**Comment by GustavoMelo40** [comment]
My error is in real a little different.
![Captura de Tela 2020-12-17 às 12 33 48](https://user-images.githubusercontent.com/23658837/102508436-25cc8600-4064-11eb-8db8-4cb7ae90dec0.png)

SOMETHING WENT WRONG
Cannot read property '0' of undefined

**Comment by GustavoMelo40** [comment]
Works!! I add _FIRETABLE_ with a settings, and in settings document, one empty array field 'tables', after this only Add New Roles
