### ISSUE TITLE
Ability to change default JSON from object to array

### ISSUE THREAD

**Issue by a-Leong** [AntlerVC/firetable#293]
**Is your feature request related to a problem? Please describe.**
When adding a JSON type column to a table, the default entry in new rows is an empty object. There is no way to configure this default entry to be an empty array. My current workaround strategy is to delete and re-add the property in Firestore with an empty array as its value. The empty array value is imported and can be worked with in Firetable as expected.

**Describe the solution you'd like**
When creating a JSON type column, an option to use either an object or an array as the default root data structure. Alternatively, split the JSON column type into two distinct column types: JSON Object and JSON Array.

**Describe alternatives you've considered**
I've considered restructuring my data to avoid any arrays containing complex data types.

**Comment by shamsmosowi** [comment]
good idea @a-Leong , I'll add it in #292
