### ISSUE TITLE
ValidationError

### ISSUE THREAD

**Issue by haythoo** [AntlerVC/firetable#317]
Hello

I created new project, using the cli, connected to my firebase account, downloaded the service account and did everything as per the instructions. I gave the ADMIN role to my email, which is created in the authentication section in firebase dashboard.

I started the project using the cli firetable start, I signed in using the email. Everything is working, the roles is there, the tables is there in firestore, but when I try to add new table on firetable frontend I get errors.

![Screen Shot 2021-03-09 at 10 41 00 AM](https://user-images.githubusercontent.com/3076507/110435390-03c32c80-80c4-11eb-9f96-9bd934bab57b.png)

![Screen Shot 2021-03-09 at 10 41 56 AM](https://user-images.githubusercontent.com/3076507/110435596-4127ba00-80c4-11eb-82ca-8cf26136288d.png)

![Screen Shot 2021-03-09 at 10 44 26 AM](https://user-images.githubusercontent.com/3076507/110435748-70d6c200-80c4-11eb-8158-55f541565003.png)

**Comment by notsidney** [comment]
Hi @haythoo, please update to v1.3.1. That version fixes this issue
