### ISSUE TITLE
【question】 How do I remove the _ ft _ createdBy and _ ft _ createdBy fields when retrieving documents from firstore?

### ISSUE THREAD

**Issue by B4129** [AntlerVC/firetable#376]
Hello. I am Japanese and cannot speak English, so I will write it through translation.

Columns such as _ ft _ createdBy are automatically registered when updating a document using Fireable, but all fields are retrieved when retrieving a document from firebase. 
I want to exclude fields automatically generated by fireTable such as _ ft _ createdBy,but I don't know how. 
Could you tell me if there is any good way?

**Comment by shamsmosowi** [comment]
Hi, we don't currently have the option to disable the  ft _ createdBy / ft _ updatedBy  fields on firetable. But depending on what programming language you're using you can remove them after receiving the document data on you're front-end.
eg: if you're using javascript you use the [delete operator](https://www.w3schools.com/howto/howto_js_remove_property_object.asp)
