### ISSUE TITLE
Keep failing in "Set up service account" step 

### ISSUE THREAD

**Issue by RezaRahmati** [AntlerVC/firetable#555]
**Describe the bug**
Setup keep failing in Setup Service account Step

**To Reproduce**
1. Go to '/setup'
2. continue wizard until you get to Service Account step
3. Try to verify service account

** Actual Behavior **
it shows error "Some roles are missing. Also make sure your Firebase project has Firestore and Authentication enabled."

**Expected behavior**
It pass the step

**Screenshots**
![image](https://user-images.githubusercontent.com/10086092/136224585-0bbceefb-a4d9-465f-9b25-bf0db468265a.png)

Here is cloud run setting
![image](https://user-images.githubusercontent.com/10086092/136224723-0a68e86e-ef75-4e93-86e5-00edec3280d2.png)

Here is that service account roles
![image](https://user-images.githubusercontent.com/10086092/136225229-d4fa5677-3bb9-4e89-bd43-295c1f1e9203.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
In that page it shows the service account should have these roles

- Service Account User
- Firebase Admin

In the setup guide in [here](https://docs.rowy.io/rowy-run) it says we need these roles

- Service Account User – required to deploy Cloud Functions
- Firebase Authentication Admin
- Firestore Service Agent

Our service account has all those roles, see the screen shots

**Comment by shamsmosowi** [comment]
Hi @RezaRahmati can you please check if both firestore and firebase auth are enabled on your project?

**Comment by RezaRahmati** [comment]
@shamsmosowi Thank you for reply. I see now.
so technically firebase auth will be reflect on gcp, it would beneficial to have a documentation how to use rowy on pure gcp projects

**Comment by RezaRahmati** [comment]
@matthewtsmith FYI, I enabled the firebase auth on our project (via creating firebase project and connecting it with current gcp project) and now it's good, and setup finished
