### ISSUE TITLE
Firetable creates _FIRETABLE_ document in existing collections

### ISSUE THREAD

**Issue by itsermin** [AntlerVC/firetable#75]
Firetable creates _FIRETABLE_ document in our existing collections and it's messing with our database and app.

Suggest to create separation between Firetable document entries and the existing database.
Eg. Place all the required Firetable documents/subcollections in the _FIRETABLE_ main collection. Don't add documents in our existing collections.
![image](https://user-images.githubusercontent.com/44114383/74199859-77c0b480-4cb9-11ea-9a4b-5c27fcabf441.png)

**Comment by shamsmosowi** [comment]
Thanks Ermin, you're right we'll probably restructure it soon. so the path would be as you suggested,
'retailers/_FIRETABE_'  would be moved to '_FIRETABLE_/retailers'

**Comment by AntlerEngineering** [comment]
@itsermin this problem is now solved thanks to @knshiro contribution
